######################################################################
# Automatically generated by qmake (2.01a) Lu mar. 31 15:17:08 2014
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += src/anki-lite-main-wnd.h src/card.hpp src/deck.hpp src/main.h
FORMS += src/anki-lite-main-wnd.ui
SOURCES += src/anki-lite-main-wnd.cpp src/card.cpp src/deck.cpp src/main.cpp
